[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/admin/config.yml"
  [headers.values]
    Content-Type = "text/yaml"

[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200
