backend:
    name: github
    repo: Neiron666/fitness-club-site
    branch: main
    base_url: https://fitness-club-il-project.netlify.app
    auth_endpoint: /api/auth

media_folder: "images/uploads" # Куда сохраняются картинки внутри репозитория
public_folder: "/images/uploads" # Как путь выглядит на сайте

collections:
    - name: "gallery"
      label: "גלריה"
      folder: "images/gallery"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "כותרת", name: "title", widget: "string" }
          - { label: "תמונה", name: "image", widget: "image" }

    - name: "prices"
      label: "מחירים"
      folder: "content/prices"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "כותרת", name: "title", widget: "string" }
          - { label: "תיאור", name: "description", widget: "text" }
          - { label: "מחיר", name: "price", widget: "string" }

    - name: "hours"
      label: "שעות פתיחה"
      folder: "content/hours"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "יום", name: "day", widget: "string" }
          - { label: "שעות", name: "hours", widget: "string" }

    - name: "news"
      label: "חדשות / עדכונים"
      folder: "content/news"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "כותרת", name: "title", widget: "string" }
          - { label: "תוכן", name: "body", widget: "markdown" }
          - { label: "תאריך", name: "date", widget: "datetime" }
